# Handlers file.
---
# handlers for httpd (Red Hat distributions)
- name: restart httpd
  service:
    name: httpd
    state: restarted
  become: True
- name: reload httpd
  service:
    name: httpd
    state: reloaded
  become: True
# handlers for apache2 (Debian distributions)
- name: restart apache2
  service:
    name: apache2
    state: restarted
  become: True
- name: reload apache2
  service:
    name: apache2
    state: reloaded
  become: True
