# Main tasks file for installing Apache web server, enabling and starting
# the web service, and configuring and populating a virtual host. Playbook
# supports Debian and Red Hat based distributions.
---
- name: Include redhat-specific Apache web server package installation tasks.
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: Include debian-specific Apache web server package installation tasks.
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
- name: Install config file for virtual host "vhost".
  template:
    src: vhost.conf.j2
    dest: "{{ apache_vhost_config_dir }}/vhost.conf"
    owner: root
    group: root
    mode: 0644
  become: True 
  notify: "{{ 'reload httpd' if ansible_facts['os_family']|lower == 'redhat' else 'reload apache2' }}"
- name: For Debian-based hosts, manage virtual sites.
  import_tasks: manage_debian_virtual_sites.yml
  when: ansible_facts['os_family']|lower == 'debian'
  become: True
- name: Create the virtual hosts root directory.
  file:
   path: "{{ vhosts_root_directory }}"
   state: directory
   mode: 0755
  become: True
- name: Create the virtual host-specific sub-directory for "vhost".
  file:
   path: "{{ vhosts_root_directory }}/{{ ansible_hostname }}"
   state: directory
   owner: "{{ vhost_user }}"
   mode: 0755
  become: True
- name: Check if virtual host "vhost" has an index.html file.
  stat:
    path: "{{ vhosts_root_directory }}/{{ ansible_hostname }}/index.html"
  register: stat_result
- name: If virtual host "vhost" does not have an index.html file, create one.
  template:
    src: index.html.j2
    dest: "{{ vhosts_root_directory }}/{{ ansible_hostname }}/index.html"
    owner: "{{ vhost_user }}"
    group: "{{ vhost_group }}"
    mode: 0644
  become: True
  when: not stat_result.stat.exists
