# Apache web server package installation steps for Red Hat based distributions.
---
- name: Install Apache "httpd" package.
  yum:
    name: httpd
    state: present
  become: True
- name: Enable "httpd" service.
  service:
    name: httpd
    state: started
    enabled: True
  become: True
