- name: template for apache 
  hosts: centos
  become: true
  vars: 
    web_root: /var/www/html
  tasks: 
     - name: apply apache template 
       template: 
            src: web.conf.j2
            dest: /etc/httpd/conf.d/web.conf
