# Playbook to that deploys a templatized /etc/motd file.
---
- hosts: centos
  vars:
    company: NetApp Lab on Demand
  tasks:
    - name: Configure message of the day
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
      become: yes
